### PR TITLE
Fix:  Error: Exposing privileged or cross-origin callable is prohibited

### PR DESCRIPTION
**Pull request by mauge123**
On firefox 41.0.1
Use of cloneInto to create obects witch accesibiility to target scope,
and waiveXrays to perform object calls

See: https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Language_Bindings/Components.utils.cloneInto

See https://developer.mozilla.org/en-US/docs/Xray_vision

Also declares on prototype are not working.

### CODE REVIEW

**Comment by aabeling** [comment]
Hi,

1. does the minimal supported version needs to be adjusted in the install.rdf?
2. would you like to take this project over? I am not working on it anymore. https://help.github.com/articles/transferring-a-repository/

Best regards
Achim

**Comment by berenddeschouwer** [comment]
If the offer of taking the project over still exists, I'd be interested.

**Comment by aabeling** [comment]
I tried to transfer the repo to you but it failed since you already have a repo with the same name.
Can you please remove your fork and then I will try again.

**Comment by berenddeschouwer** [comment]
I've renamed my repo.  Please try again.

I'll also attempt to pull this request, and update addons.mozilla.org

**Comment by aabeling** [comment]
It still fails with the message
"berenddeschouwer already has a repository in the aabeling/commandrun network ".

github says
"The target account must not have a repository with the same name, or a fork in the same network."

I think you will have to delete your fork.

**Comment by berenddeschouwer** [comment]
Deleted

**Comment by berenddeschouwer** [comment]
I've commited this with a small whitespace fix, and by upping the minimum Firefox version to 28.  Firefox 28 added cloneInto()

**Comment by berenddeschouwer** [comment]
This is now on addons.mozilla.org; and should work for Firefox 28 -> 45 (ESR)

It doesn't yet work for Firefox 50, for different reasons.

**Pull request closed without merging**
